### ISSUE TITLE
Error message test-config.py

### ISSUE THREAD

**Issue by Autoschrauberix** [s10l/dbus-deye-sun-g3-pvinverter#3]
I changed the config.ini and I think I have a connection but the there ist an error in the following, I have a sun-2000-G3 but I think it is equal to the 1600. The problem can be that I have Firmware Version MW3_16U_5406_1.57

Error Message:

root@raspberrypi2:/data/dbus-deye-sun-g3-pvinverter# ./test-config.py
2023-11-12 07:20:40,525 root INFO config...
2023-11-12 07:20:40,527 root INFO 192.168.178.---
2023-11-12 07:20:40,529 root INFO 8899
2023-11-12 07:20:40,531 root INFO 418346-----
Traceback (most recent call last):
  File "./test-config.py", line 126, in <module>
    main()
  File "./test-config.py", line 19, in main
    data = _getDeyeData()
  File "./test-config.py", line 36, in _getDeyeData
    modbus = PySolarmanV5(
  File "/data/dbus-deye-sun-g3-pvinverter/pysolarmanv5/pysolarmanv5.py", line 108, in __init__
    self._v5_frame_def()
  File "/data/dbus-deye-sun-g3-pvinverter/pysolarmanv5/pysolarmanv5.py", line 126, in _v5_frame_def
    self.v5_loggerserial = struct.pack("<I", self.serial)
struct.error: argument out of range
root@raspberrypi2:/data/dbus-deye-sun-g3-pvinverter#

**Comment by s10l-sap** [comment]
Did you set up the following fields? These are mandatory fields.

```
Address=192.168.1.127
Serial=1234567890
```

in https://github.com/s10l/dbus-deye-sun-g3-pvinverter/blob/main/config.ini#L2-L3

Be sure that you can reach the device from machine running this script.

You can test connection it with:
- ping <ip> // should respond
- curl <ip> // should display the login page html
- netcat <ip> 8899 // should connect, does not display anything

Maybe firewall rules are blocking access. eg. wifi client isolation in guest networks or custom rules.
Try within same wifi network (non guest network) first.

My Deye is connected to dedicated deye wifi guest network that block all traffic from and to the Deye inverter, except VenusOS to Deye on port 8899 + ICMP  and my private machine accessing port 80 + ICMP.
